// shared/editor/src/vue/TipTapRenderer.vue
<script setup lang="ts">
/**
 * Vue 3 TipTap 렌더러 (MathJax 통합)
 */

import { ref, onMounted } from 'vue'
import StarterKit from '@tiptap/starter-kit'
import { Editor, EditorContent } from '@tiptap/vue-3'
import { MathInline, MathBlock } from '../mathNodes'
import { useMathJaxTypeset } from './useMathJaxTypeset'
import { typesetQueued } from '../mathjaxUtils'

const props = defineProps<{ content: any }>()
const containerRef = ref<HTMLElement | null>(null)

const editor = new Editor({
  editable: false,
  extensions: [StarterKit, MathInline, MathBlock],
  content: props.content,
})

useMathJaxTypeset(containerRef, [props.content])

onMounted(() => {
  editor.on('update', () => typesetQueued(containerRef.value ?? undefined))
})
</script>

<template>
  <div ref="containerRef">
    <EditorContent :editor="editor" />
  </div>
</template>

// shared/editor/src/react/TipTapRenderer.tsx
/**
 * React TipTap 렌더러 (MathJax 통합)
 */

import React, { useEffect, useRef } from "react";
import { EditorContent, useEditor } from "@tiptap/react";
import StarterKit from "@tiptap/starter-kit";
import { MathInline, MathBlock } from "../mathNodes";
import { useMathJaxTypeset } from "./useMathJaxTypeset";
import { typesetQueued } from "../mathjaxUtils";

type Props = { content: any };

export default function TipTapRenderer({ content }: Props) {
  const containerRef = useRef<HTMLDivElement>(null);
  const editor = useEditor({
    editable: false,
    extensions: [StarterKit, MathInline, MathBlock],
    content,
    onUpdate: () => {
      typesetQueued(containerRef.current ?? undefined);
    },
  });

  // content가 바뀌거나 editor가 초기화될 때 typeset
  useMathJaxTypeset([content, editor?.state?.doc], containerRef.current);

  return (
    <div ref={containerRef}>
      <EditorContent editor={editor} />
    </div>
  );
}
